# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stm_app', '0002_auto_20170227_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='person',
        ),
    ]
