# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stm_app', '0003_auto_20170227_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='person',
            new_name='persons',
        ),
    ]
