# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm_app', '0005_auto_20170228_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='project',
        ),
        migrations.RemoveField(
            model_name='split',
            name='split',
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ManyToManyField(to='stm_app.Project'),
        ),
        migrations.DeleteModel(
            name='Split',
        ),
    ]
