# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stm_app', '0006_auto_20170228_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='project',
        ),
        migrations.AddField(
            model_name='join',
            name='join',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stm_app.Person'),
        ),
        migrations.AddField(
            model_name='join',
            name='project',
            field=models.ManyToManyField(to='stm_app.Project'),
        ),
    ]
