# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm_app', '0007_auto_20170228_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='join',
        ),
        migrations.RemoveField(
            model_name='join',
            name='project',
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ManyToManyField(to='stm_app.Project'),
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
