# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm_app', '0008_auto_20170228_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(to='stm_app.Person'),
        ),
    ]
