# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stm_app', '0010_auto_20170228_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='manager',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
