# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stm_app', '0012_auto_20170302_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='project_id',
            new_name='id_project',
        ),
    ]
